spring.application.name=StockController

# Conexi�n a la base de datos MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/stock_controller_db
spring.datasource.username=root
spring.datasource.password=claudio
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080
logging.level.org.springframework.jdbc=debug
logging.level.com.zaxxer.hikari=debug